### ISSUE TITLE
Housing-data-challenge-Ruby

### ISSUE THREAD

**Issue by paulroberts68** [bcgov/housing-data-challenge-ruby#1]
<div id="devex-badge">
<a rel="Delivery" href="https://github.com/BCDevExchange/docs/blob/master/discussion/projectstates.md"><img alt="In production, but maybe in Alpha or Beta. Intended to persist and be supported." style="border-width:0" src="https://assets.bcdevexchange.org/images/badges/delivery.svg" title="In production, but maybe in Alpha or Beta. Intended to persist and be supported." /></a>
</div>
---

## Background

The Province of British Columbia and other agencies collect a wealth of administrative data that relates to housing, including the market for housing, as a consequence of their regulatory and administrative authorities. These include data about legal ownership (Land Titles BC), the total stock of housing (BC Assessment), and taxation information (Ministry of Finance). In addition, socio-demographic information is available, such as ownership status (owner or renter), through the Census of Canada.

The British Columbia Government seeks to develop statistics that will provide greater certainty about the state of housing in the province, including the role of foreign ownership, real estate as an investment or business strategy (rather than home ownership), and insights into the regional impact of these issues. For more information see https://github.com/bcgov/housing-data-visualization-project. 

We are offering this issue as a paid opportunity through our [experimental procurement model, Code-with-Us](https://github.com/BCDevExchange/code-with-us/wiki/1.-Intro-&-Disclaimer) and under the following terms [Code-with-Us Terms](https://github.com/BCDevExchange/devex/blob/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf) {PDF}.

## User Story

Government, infrastructure planners and the wider public need to interact with an online visualization platform of B.C. housing market information (using the following types of data: population data, property assessments, property transfer tax records, home owner grant records, land title records, etc.) so that they understand and make decisions based on community growth and housing data.

## Acceptance Criteria

To be paid for this opportunity meet the following criteria:

* The code is mounted in a Province of B.C. GitHub repository under an open source license.
  - Preference is for [Apache 2.0](http://www.apache.org/licenses/LICENSE-2.0).

* Should be able to use Property Transfer Tax data: [https://catalogue.data.gov.bc.ca/dataset/property-transfer-tax-data](https://catalogue.data.gov.bc.ca/dataset/property-transfer-tax-data). 
  - These data are licensed under the [B.C. Government Open Data License](http://www2.gov.bc.ca/gov/content/governments/about-the-bc-government/databc/open-data/open-government-license-bc).

* Should be able to use Census data: 
  - preference is for demographics at the Census Tract level, but the ability to aggregate to higher levels of geography (e.g. municipality) would be desirable.
  - see the [2011 Census of Population data products page](http://www12.statcan.gc.ca/census-recensement/2011/dp-pd/index-eng.cfm)
  - link to [Census geography files, including boundary (shape) files](http://www12.statcan.gc.ca/census-recensement/2016/geo/index-eng.cfm)
  - these data and supplementary files are licensed under the [Statistics Canada Open Licence](http://www.statcan.gc.ca/eng/reference/licence).

* Should be able to use BC Assessment data (geocoded to Census geographies; assuming availability)

* Code can be run from the instructions given (e.g. from readme file)

* Must have final delivery on March 7th, with initial milestones for code commits in GitHub on February 17th and March 3rd for feedback.

## Evaluation Criteria

Your **visualization** will be scored on the following (60 points total):

* Function: how easy is it to navigate and interact with the visualization (15 points).

* Story: how does the visualization use narrative to make the data relevant and meaningful for the audience (15 points).

* Design: how does the visualization use best design practice (e.g. good design principles, visual cues, hierarchy) so that the meaning is clear (15 points).

* Data Analysis: how does the visualization uncover patterns and relationships in the data (15 points).

**Code** will be scored on the following (40 points total):

* Instructions on how to install and run the code (5 points).

* Is the code documented (literate programming; maintainability) (10 points).

* Does the code run on the Province of B.C. DevOps platform (a Docker / OpenShift environment). This is much easier if you setup up the infrastructure before you start coding (5 points).

* How transferable (extensible) is the code to analyze and visualize other government data (10 points).

* Processing efficiency / responsive (5 points)

* Runs on desktop required; bonus for tablet (5 points).

### Useful links

[How payment works](https://github.com/BCDevExchange/code-with-us/wiki/5.-How-payment-works)
[Original competition description](https://github.com/bcgov/housing-data-visualization-project)

**Comment by MonkmanMH** [comment]
Note change in dates and Code evaluation scoring.

**Comment by MonkmanMH** [comment]
Thanks for participating in the tech challenge!
