### ISSUE TITLE
shelter cost ratios

### ISSUE THREAD

**Issue by MonkmanMH** [bcgov/housing-data-challenge-ruby#5]
Data file [https://github.com/bcgov/housing-data-challenge-ruby/blob/master/census_data/NHS_99-014-X2011031_sheltercostratio.csv](https://github.com/bcgov/housing-data-challenge-ruby/blob/master/census_data/NHS_99-014-X2011031_sheltercostratio.csv) now added, with the 2011 National Household Survey (NHS) shelter cost ratio data for each Census Metropolitan Area (CMA) in Canada

**Comment by sasha-ruby** [comment]
This has been superseded by Census 2016 data.
