### ISSUE TITLE
mobility data

### ISSUE THREAD

**Issue by MonkmanMH** [bcgov/housing-data-challenge-ruby#6]
Comprehensive mobility data now added, from 2011 National Household Survey
* [Dissemination Area](https://github.com/bcgov/housing-data-challenge-ruby/blob/master/census_data/pop_mobility_DA.feather)
* [Census Division (Regional District) and Census Subdivision (includes municipalities)](https://github.com/bcgov/housing-data-challenge-ruby/blob/master/census_data/pop_mobility_CDCSD.feather)

Note that both files are in "feather" format; for more information, see ["Feather: A Fast On-Disk Format for Data Frames for R and Python"](https://blog.rstudio.com/2016/03/29/feather/)

**Comment by sasha-ruby** [comment]
This has been superseded by Census 2016 data.
